name: Go

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
#        go: ['1.15.x', '1.16.x', '1.17.x']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
 #         go-version: ${{ matrix.go }}
           check-latest: true

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          path: src/github.com/ikawaha/waifu2x.go

      - name: Build
        run: go build -v ./...
        working-directory: src/github.com/ikawaha/waifu2x.go

      - name: Test
        run: |
          go test -v ./...
        working-directory: src/github.com/ikawaha/waifu2x.go

      - name: Benchmark
        run: |
          go test -v -bench ./...
        working-directory: src/github.com/ikawaha/waifu2x.go
